[package]
name = "intopt"
version = "0.5.0"
authors = ["Tim Weißenfels <tim.weissenfels@stu.uni-kiel.de>"]
edition = "2018"

[dependencies]
num-traits = "0.2"
hashbrown = "0.7"
clap = "2.33"
pest = "2.1"
pest_derive = "2.1"
