WHITESPACE  = _{ " " }
integer     = @{ "-"? ~ ASCII_DIGIT+ }
variable    = { ASCII_ALPHA ~ ASCII_ALPHANUMERIC* }
multiple    = { (integer ~ "*")? ~ variable }
term        = { multiple | integer }
sum         = { (term ~ "+" ~ sum) | term }
equation    = { sum ~ "=" ~ sum }
constraints = { (equation ~ NEWLINE ~ constraints) | equation }
ilp         = {    
    SOI ~ ^"maximize:" ~ NEWLINE 
    ~ sum ~ NEWLINE
    ~ ^"subject to:" ~ NEWLINE
    ~ constraints ~ NEWLINE*
    ~ EOI
}